import numpy as np
from scipy.integrate import odeint
import matplotlib.pyplot as plt

def binding_prob(x, kd, n):
  """
  

  Parameters
  ----------
  x : TYPE
    Quantity (e.g. concentration) of the protein
  kd : TYPE
    K_off/K_on, disassociation constant
  n : TYPE
    Hill coefficient.

  Returns
  -------
  None.

  """
  return x**n / (kd**n + x**n)

def HillCube(x, kd, n, normalized=False):
  """
  function that is implemented in ODEfy

  Parameters
  ----------
  x : TYPE
    DESCRIPTION.
  kd : TYPE
    DESCRIPTION.
  n : TYPE
    DESCRIPTION.
  normalized : TYPE, optional
    DESCRIPTION. The default is False.

  Returns
  -------
  TYPE
    DESCRIPTION.

  """
  if normalized == True:
    return binding_prob(x, kd, n) / binding_prob(1, kd, n)
  else:
    return binding_prob(x, kd, n)

def tick_time(t_start, t_end, time_step):
  """
  

  Parameters
  ----------
  t_start : TYPE
    The first time point to be solved
  t_end : TYPE
    The last time point to be solved
  time_step : TYPE
    How often the ODE model will be solved

  Returns
  -------
  numpy array
    Time points that to be solved

  """
  t_min = t_start; t_max = t_end; dt = time_step
  return np.arange(t_min, t_max+dt, dt)

def solve_pdd(ode_mod, x0, pars, ts):
  """
  

  Parameters
  ----------
  ode_mod : TYPE
    ODE model for proliferation differentiation decision
  x0 : list
    Initial values
  pars : tuple
    Parameters used by the ODE model
  ts : TYPE
    Time points that to be solved. Generated by tick_time().

  Returns
  -------
  TYPE
    DESCRIPTION.

  """
  ts = ts
  x0 = x0
  return odeint(ode_mod, x0, ts, args=pars)

def sketch_ppd(xt, proliferation, differentiation, ts):
  """
  

  Parameters
  ----------
  xt : numpy array
    Solution produced by solve_pdd()
  proliferation : TYPE
    Proliferation activity calculated by rate_proliferation()
  differentiation : TYPE
    Differentiation activity calculated by rate_differentiation()
  ts : TYPE
    Time points that are generated by tick_time()

  Returns
  -------
  Line plots with one column facet. 

  """
  
  fig, ax = plt.subplots(5,1)

  ax[0].plot(ts, xt[:,0], color='k')
  ax[0].set_xlabel('Hour')
  ax[0].set_ylabel('mls-2')
  ax[0].set_xticks(np.arange(0, 20+2, 2))

  ax[1].plot(ts, xt[:,1], color='k')
  ax[1].set_xlabel('Hour')
  ax[1].set_ylabel('hlh-1')
  ax[1].set_xticks(np.arange(0, 20+2, 2))

  ax[2].plot(ts, xt[:,2], color='k')
  ax[2].set_xlabel('Hour')
  ax[2].set_ylabel('fos-1')
  ax[2].set_xticks(np.arange(0, 20+2, 2))

  ax[3].plot(ts, xt[:,3], color='g', label='cyd-1')
  ax[3].plot(ts, xt[:,4], color='r', label='cki-1')
  ax[3].set_xlabel('Hour')
  ax[3].legend()
  ax[3].set_xticks(np.arange(0, 20+2, 2))
  
  ax[4].plot(ts, proliferation, color='k',linestyle='-', label='proliferation')
  ax[4].plot(ts, differentiation, color='k', linestyle=':', label='differentiation')
  ax[4].set_xlabel('Hour')
  ax[4].set_xticks(np.arange(0,20+2,2))
  ax[4].legend()

  plt.show()
  